import Link from "next/link";
import { ArrowRight, Check, Code2, PanelsTopLeft, Workflow } from "lucide-react";
import { Header } from "./header";
import { MediaFrame } from "./media-frame";
import { Pressable, Reveal } from "./motion";
import { QuoteForm } from "./quote-form";
import { publishedCases } from "@/content/cases";
import { site, whatsappUrl } from "@/lib/site";

const services = [
  { n: "01", icon: PanelsTopLeft, title: "Sites & Landing Pages", text: "Experiências digitais modernas, responsivas e pensadas para transformar visitantes em oportunidades.", tags: "Design moderno • SEO • Performance • Conversão" },
  { n: "02", icon: Code2, title: "Sistemas & Plataformas", text: "Sistemas web, dashboards e soluções SaaS desenvolvidos de acordo com a realidade da sua empresa.", tags: "Dashboards • SaaS • APIs • PostgreSQL" },
  { n: "03", icon: Workflow, title: "Automações & Integrações", text: "Fluxos e integrações que reduzem trabalho manual, diminuem erros e aceleram sua operação.", tags: "WhatsApp • E-mail • APIs • Webhooks" },
];
const plans = [
  { name: "Landing Page", price: "R$ 990", desc: "Uma página estratégica para apresentar uma oferta ou serviço com clareza e conversão.", features: ["Página única personalizada", "Responsivo", "WhatsApp e formulário", "SEO básico", "Publicação"] },
  { name: "Site Institucional", price: "R$ 1.490", desc: "Uma presença digital profissional para apresentar sua empresa e seus serviços.", features: ["Estrutura institucional", "Design personalizado", "Responsivo", "Contato e WhatsApp", "SEO básico"] },
  { name: "Site Premium", price: "R$ 2.490", desc: "Uma experiência digital completa para empresas que querem se destacar.", features: ["Visual exclusivo", "Páginas internas", "Animações e interações", "Performance", "Integrações externas"], featured: true },
];
const process = ["Descoberta", "Planejamento", "Design & Desenvolvimento", "Revisão & Entrega", "Suporte"];
const faqs = [
  ["Quanto tempo leva para desenvolver um projeto?", "O prazo depende da complexidade. Landing pages e sites menores costumam ser mais rápidos; sistemas exigem uma análise detalhada antes do cronograma."],
  ["O site funciona bem no celular?", "Sim. Todos os projetos são desenvolvidos com foco em responsividade e boa experiência em smartphones, tablets e computadores."],
  ["Domínio e hospedagem estão inclusos?", "A configuração pode ser feita durante o projeto. Custos de domínio, hospedagem ou serviços externos são informados separadamente antes da contratação."],
  ["Vocês desenvolvem sistemas personalizados?", "Sim. Sistemas web, dashboards, áreas administrativas, SaaS, integrações e automações são analisados e orçados conforme a necessidade."],
  ["O que acontece depois da entrega?", "Você pode contratar o plano de Manutenção & Suporte por R$ 199/mês para manter o projeto acompanhado."],
];
export function Home() {
  const mainCase = publishedCases[0];
  return <><Header /><main>
    <section className="hero"><div className="hero-glow" /><div className="shell hero-grid"><Reveal className="hero-copy"><p className="eyebrow">{site.founder} · {site.role}</p><h1>Tecnologia que transforma ideias em <span>soluções reais.</span></h1><p className="lead">Sites, sistemas e automações desenvolvidos sob medida para empresas que querem crescer, vender mais e trabalhar de forma mais inteligente.</p><div className="actions"><a className="button" href={whatsappUrl("Olá, Julio! Vim pelo site da Dassaevy Labs e gostaria de conversar sobre um projeto.")} target="_blank">Falar comigo no WhatsApp <ArrowRight size={18} /></a><a className="button ghost" href="#contato">Solicitar orçamento</a></div><p className="hero-points">Sites modernos · Sistemas sob medida · Automações inteligentes</p></Reveal><Reveal className="hero-photo" delay={0.12}><MediaFrame src="/images/julio-dassaevy.webp" alt="Julio Dassaevy" width={500} height={889} priority /></Reveal></div><div className="ticker">DESIGN • DEVELOPMENT • AUTOMATION • DIGITAL EXPERIENCES • DESIGN • DEVELOPMENT • AUTOMATION • DIGITAL EXPERIENCES</div></section>
    <section className="section shell"><Reveal><p className="eyebrow">SOLUÇÕES DIGITAIS</p><h2>Mais do que presença digital.</h2><p className="section-lead">Eu desenvolvo soluções digitais pensadas para resolver problemas reais do seu negócio — de uma landing page que converte até sistemas completos e automações que reduzem trabalho manual.</p></Reveal></section>
    <section id="servicos" className="section shell"><div className="service-list">{services.map((s, i) => <Reveal key={s.n} delay={i * .05}><article className="service-card"><span className="service-number">{s.n}</span><s.icon /><h3>{s.title}</h3><p>{s.text}</p><small>{s.tags}</small></article></Reveal>)}</div></section>
    <section id="projetos" className="section shell"><Reveal><p className="eyebrow">PROJETOS</p><h2>Soluções que já estão funcionando no mundo real.</h2></Reveal><Pressable className="case-card"><Link href={`/projetos/${mainCase.slug}`}><div><p className="eyebrow">{mainCase.eyebrow}</p><h3>{mainCase.title}</h3><p>{mainCase.summary}</p><span>Ver case completo →</span></div>{mainCase.image && <MediaFrame {...mainCase.image} />}</Link></Pressable></section>
    <section id="precos" className="section shell"><Reveal><p className="eyebrow">INVESTIMENTO</p><h2>Escolha o ponto de partida ideal.</h2><p className="section-lead">Valores base para projetos comuns. Sistemas, automações e escopos especiais recebem orçamento personalizado.</p></Reveal><div className="pricing-grid">{plans.map((p) => <Pressable key={p.name} className={`price-card ${p.featured ? "featured" : ""}`}><p className="eyebrow">{p.featured ? "MAIS COMPLETO" : "PROJETO"}</p><h3>{p.name}</h3><p>{p.desc}</p><div className="price"><small>A partir de</small><strong>{p.price}</strong></div><ul>{p.features.map(f => <li key={f}><Check size={16} />{f}</li>)}</ul><a className="button ghost full" href={whatsappUrl(`Olá, Julio! Vi o pacote ${p.name} no site da Dassaevy Labs e gostaria de conversar sobre um projeto.`)} target="_blank">Quero este projeto</a></Pressable>)}</div><Reveal><div className="custom-card"><div><p className="eyebrow">PROJETO PERSONALIZADO</p><h3>Precisa de algo além de um site?</h3><p>Sistemas web, dashboards, plataformas SaaS, áreas administrativas, integrações e automações são desenvolvidos sob medida.</p></div><a className="button" href="#contato">Solicitar orçamento personalizado</a></div></Reveal></section>
    <section className="section shell"><Reveal><div className="maintenance"><div><p className="eyebrow">MANUTENÇÃO & SUPORTE</p><h2>Seu projeto não termina na entrega.</h2><p>Suporte técnico, monitoramento, atualizações, backups, manutenção preventiva, pequenos ajustes e prioridade no atendimento.</p></div><div className="maintenance-price"><strong>R$ 199</strong><span>/mês</span><small>Sem fidelidade obrigatória</small></div></div></Reveal></section>
    <section id="sobre" className="section shell about-grid"><Reveal><MediaFrame src="/images/julio-dassaevy.webp" alt="Julio Dassaevy, fundador da Dassaevy Labs" width={500} height={889} /></Reveal><Reveal><p className="eyebrow">SOBRE</p><h2>Tecnologia com visão de negócio.</h2><p className="section-lead">Sou Julio Dassaevy, desenvolvedor Full Stack e fundador da Dassaevy Labs. Trabalho criando soluções digitais que unem desenvolvimento, experiência do usuário e estratégia.</p><p>Meu objetivo não é apenas entregar código. É entender o problema, transformar a necessidade em uma solução clara e construir algo que faça sentido para o negócio.</p></Reveal></section>
    <section className="section shell"><Reveal><p className="eyebrow">PROCESSO</p><h2>Você acompanha o projeto do início ao fim.</h2></Reveal><ol className="process">{process.map((item, i) => <li key={item}><span>{String(i + 1).padStart(2, "0")}</span><div><h3>{item}</h3><p>{["Entendemos o objetivo, público e problema.", "Definimos estrutura, funcionalidades e tecnologia.", "A solução ganha forma com foco em experiência e performance.", "Validamos detalhes, ajustamos e publicamos.", "O projeto pode continuar acompanhado após a entrega."][i]}</p></div></li>)}</ol></section>
    <section className="section shell"><Reveal><p className="eyebrow">FAQ</p><h2>Dúvidas frequentes.</h2></Reveal><div className="faq">{faqs.map(([q, a]) => <details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</div></section>
    <section id="contato" className="section shell contact-grid"><Reveal><p className="eyebrow">VAMOS CONVERSAR</p><h2>Tem uma ideia? Vamos transformar em algo real.</h2><p className="section-lead">Conte o que sua empresa precisa e vamos encontrar a melhor forma de transformar isso em uma solução digital.</p><a className="text-link" href={whatsappUrl("Olá, Julio! Quero conversar sobre um projeto para minha empresa.")} target="_blank">Prefere WhatsApp? Fale comigo agora →</a></Reveal><QuoteForm /></section>
  </main><footer className="footer"><div className="shell footer-grid"><div><div className="brand"><span className="brand-mark">D</span><span>Dassaevy Labs</span></div><p>Sites • Sistemas • Automações</p></div><div><p>{site.founder}<br />Full Stack Developer & Founder</p><p><a href={site.linkedin}>LinkedIn</a> · <a href={site.github}>GitHub</a> · <a href={`mailto:${site.email}`}>E-mail</a></p></div><div><p>© 2026 Dassaevy Labs.<br />Todos os direitos reservados.</p></div></div></footer></>;
}
